# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Beauty' do

  pod 'GPUImage', '~> 0.1.7'

  target 'BeautyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BeautyUITests' do
    # Pods for testing
  end

end
